---
      - name: Install packages
        apt:
          update_cache: yes
          pkg: 
              - vim
              - curl
              - jq
              - unzip

      # https://medium.com/@pierangelo1982/install-docker-with-ansible-d078ad7b0a54
      - name: install docker dependency
        apt:
          name: "{{item}}"
          state: present
          update_cache: yes
        loop:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
      
      - name: add GPG key
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present 
          
      - name: add docker repository to apt
        apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu bionic stable
          state: present   
      
      - name: install docker
        apt:
          name: "{{item}}"
          state: latest
          update_cache: yes
        loop:
          - docker-ce
          - docker-ce-cli 
          
      - name: Start docker as a service
        service:
          name: docker
          state: started
          enabled: yes    
          

   