- name: Download  nomad
  get_url:
    url: https://releases.hashicorp.com/nomad/0.9.5/nomad_0.9.5_linux_amd64.zip
    dest: /tmp/nomad.zip
    mode: 0755

- name: Unzip nomad
  unarchive:
    src: /tmp/nomad.zip
    dest: /usr/bin
    mode: 0755
    remote_src: yes

- name: Create the /etc/nomad.d directory
  file:
    path: /etc/nomad.d
    state: directory
    mode: "a+w"

- name: Copy nomad files to /etc/nomad.d
  copy:
    src: /vagrant/ansible/playbooks/roles/nomad/files/nomad-server-east.hcl
    dest: /etc/nomad.d/nomad-server-east.hcl
    remote_src: yes

- name: Copy nomad files to systemd directory
  copy:
    src: /vagrant/ansible/playbooks/roles/nomad/files/nomad.service
    dest: /etc/systemd/system/nomad.service  
    remote_src: yes

- name:  Restart the nomad service
  service:
    name: nomad.service
    state: restarted