---
      - name: install dnsmasq
        apt:
          name: dnsmasq
    
      - name: Stop systemd-resolved.service
        service:
          name: systemd-resolved
          state: stopped
          enabled: no

      - name: cope dnsmasq conf files
        copy:
          src: /vagrant/ansible/files/dnsmasq/dnsmasq_conf
          dest: /etc/dnsmasq.d/default
          remote_src: yes 
       
      - name: Restart dnsmasq
        service:
          name: dnsmasq
          state: started
          enabled: yes  
          
      - name: Remove /etc/resolve.conf
        file:
           path: /etc/resolv.conf
           state: absent    